export default {
  root: {
    backgroundColor: "white",
    border: "2px solid black",
    borderRadius: "5px",
    padding: "0.5rem",
    position: "relative",
    cursor: "pointer",
    // overflow: "'hidden",
    "&:hover svg": {
      opacity: 1,
    },
  },
  colors: {
    backgroundColor: "#dae1e4",
    height: "120px",
    width: "100%",
    borderRadius: "5px",
    overflow: "hidden",
  },
  title: {
    display: "flex",
    justifyContent: "'space-between",
    margin: "0",
    color: "black",
    paddingTop: "0.5rem",
    // fontSize: "1rem",
    position: "relative",
  },
  emoji: {
    marginLeft: "auto",
    fontSize: "1rem",
  },
  miniColor: {
    height: "25%",
    width: "20%",
    display: "inline-block",
    margin: "0 auto",
    position: "relative",
    marginBottom: "-4px",
  },
  deleteIcon: {
    color: "white",
    backgroundColor: "#eb3d30",
    width: "30px",
    height: "30px",
    position: "absolute",
    right: "0px",
    top: "0px",
    padding: "3px",
    zIndex: 10,
    opacity: 0,
    transition: "all 0.3s ease-in-out",
  },
};
